class SubCategory {
  final String main;
  final List<String> sub;

  SubCategory({required this.main, required this.sub});
}

final sub_categories = [
  SubCategory(
    main: "Building Materials",
    sub: [
      "Cement & Bricks",
      "Stones & Sand",
      "Roofing & Precast",
      "Other Building Materials",
      "Timber & Boards",
      "Steel, Metal",
      "Building Equipment",
      "Screws, Nails & Fasteners",
      "Ladders & Scaffolding",
    ],
  ),
  SubCategory(
    main: "Security Products",
    sub: [
      "Security Gates & Bars",
      "Electric Fencing & Razor Wire",
      "Other Security Products",
      "CCTV & Security Cameras",
      "Alarm Systems & Sensors",
    ],
  ),
  SubCategory(
    main: "Boreholes & Plumbing Products",
    sub: [
      "Pumps & Pressure Gauges",
      "Water Tanks",
      "Other Plumbing Products",
      "Pipes, Valves & Connectors",
      "Geysers & Driptrays",
      "Boreholes",
    ],
  ),
  SubCategory(
    main: "Floors, Walls & Ceilings",
    sub: [
      "Floor & Wall Tiles",
      "Paint & Brushes",
      "Other Flooring",
      "Ceilings",
      "Wallpaper",
    ],
  ),
  SubCategory(
    main: "Solar Panels & Batteries",
    sub: ["Solar Inverters", "Solar Batteries", "Solar Panels"],
  ),
  SubCategory(
    main: "Windows & Doors",
    sub: ["Doors & Door Frames", "Windows & Frames"],
  ),
  SubCategory(
    main: "Lighting & Electrical",
    sub: [
      "Solar Lights",
      "Lights",
      "Electrical Equipment",
      "Electrical Cables",
      "Switches & Sockets",
    ],
  ),
  SubCategory(
    main: "Bathroom",
    sub: [
      "Showers",
      "Bathroom Fittings",
      "Toilets & Bidets",
      "Baths",
      "Basins & Vanities",
      "Taps & Mixers",
    ],
  ),
  SubCategory(
    main: "Building Tools",
    sub: ["Power Tools", "Hand Tools", "Tool Sets & Boxes"],
  ),
  SubCategory(
    main: "Kitchen",
    sub: [
      "Kitchen Cupboards & Cabinets",
      "Kitchen Fittings",
      "Complete Kitchens",
      "Countertops & Benches",
      "Kitchen Sinks",
    ],
  ),
  SubCategory(
    main: "Cars",
    sub: [
      "Toyota",
      "Mercedes",
      "Nissan",
      "Honda",
      "Mazda",
      "Bmw",
      "Isuzu",
      "Ford",
      "Vw",
      "Land-Rover",
      "Jeep",
      "Other",
      "Audi",
      "Chevrolet",
      "Mitsubishi",
      "Subaru",
      "Volvo",
      "Lexus",
      "Suzuki",
      "Hyundai",
    ],
  ),
  SubCategory(
    main: "Car Parts",
    sub: [
      "Tyres, Mags & Wheels",
      "Body Parts",
      "Auto Tools & Equipment",
      "Steering & Suspension",
      "Exterior Accessories",
      "Vehicle Security",
      "Service Parts",
      "Car Breakers",
      "Engine & Drive Train Parts",
      "Head Lights",
      "Car Batteries & Electrics",
      "Brakes & Clutches",
      "Fuel, Oils & Lubricants",
      "Cooling & Aircon",
      "Interior Accessories",
      "Other Car Parts",
      "Boat Parts & Accessories",
      "Vehicle Sound Systems",
      "Truck & Trailer Spares",
    ],
  ),
  SubCategory(
    main: "Trucks & Trailers",
    sub: [
      "Drop Side",
      "Box Body",
      "Horse Only",
      "Curtain Sider",
      "Freezer & Chiller",
      "Tippers & Sliders",
      "Trailers & Caravans",
      "Flat Deck",
      "Tankers",
      "Other Trucks & Lorries",
      "Crane",
      "Car Transporter",
    ],
  ),
  SubCategory(
    main: "Boats & Leisure",
    sub: [
      "Marine Engines & Accessories",
      "Motorboats",
      "Jetskis",
      "Other Boats & Leisure",
    ],
  ),
  SubCategory(
    main: "Vans & Buses",
    sub: [
      "16 - 25 Seats",
      "Other Vans & Buses",
      "Up To 15 Seats",
      "Over 45 Seats",
      "26 - 35 Seats",
    ],
  ),
  SubCategory(
    main: "Tractors & Heavy Equipment",
    sub: ["Tractors", "Heavy Equipment", "Heavy Equipment, Machinery"],
  ),
  SubCategory(
    main: "Motorbikes",
    sub: ["Off-Road Bikes", "Road Bikes", "Other Bikes", "Scooters"],
  ),
  SubCategory(
    main: "Other Vehicles",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Office Furniture & Supplies",
    sub: [
      "Office Chairs",
      "Office Desks",
      "Stationery & Paper",
      "Office Equipment",
      "Office Cabinets",
    ],
  ),
  SubCategory(
    main: "Farming & Agriculture",
    sub: [
      "Farming Equipment",
      "Livestock, Poultry & Fish",
      "Other Farming Products",
      "Commodities & Stockfeed",
      "Seeds, Fertilizer & Chemicals",
      "Harvesting, Post-Harvest",
      "Fertilizing, Pest Control",
      "Loading, Handling",
    ],
  ),
  SubCategory(
    main: "Store & Catering Equipment",
    sub: [
      "Catering Equipment",
      "Scales & Weighing",
      "Other Store & Catering Equipment",
    ],
  ),
  SubCategory(
    main: "Protective Clothing & Uniforms",
    sub: [
      "Work Uniforms & Safety Gear",
      "Helmets, Face Masks & Goggles",
      "Work & Safety Gloves",
      "Work Boots",
    ],
  ),
  SubCategory(
    main: "Manufacturing & Engineering",
    sub: [
      "Machinery",
      "Engineering",
      "Supplies",
      "Other Manufacturing & Engineering",
    ],
  ),
  SubCategory(
    main: "Generators",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Mining Equipment & Supplies",
    sub: ["Compressors", "Mining Equipment"],
  ),
  SubCategory(
    main: "Other Commercial Supplies",
    sub: [],
  ),
  SubCategory(
    main: "Containers",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Business for Sale",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Cellphones",
    sub: [
      "Samsung",
      "Iphone",
      "Huawei",
      "Itel",
      "Nokia",
      "Other",
      "Tecno",
      "Xiaomi",
      "Caterpillar",
      "Infinix",
    ],
  ),
  SubCategory(
    main: "Computer Accessories",
    sub: [
      "Routers, Servers & Networking",
      "Other Computer Accessories",
      "Hard Drives",
      "Keyboards & Mice",
      "Laptop Bags",
      "Computer Cables",
      "USB Memory Sticks",
      "Laptop Chargers & Batteries",
      "Monitors & Screens",
      "UPS & Surge Protection",
      "Graphics Cards",
    ],
  ),
  SubCategory(
    main: "Laptops",
    sub: ["Hp", "Dell", "Lenovo", "Apple", "Acer", "Other", "Asus", "Windows"],
  ),
  SubCategory(
    main: "Printer Consumables",
    sub: ["Printer Cartridges", "Other Printer Accessories", "Laser Toner"],
  ),
  SubCategory(
    main: "TVs & Decoders",
    sub: ["TVs", "TV Accessories", "Decoders & Dishes"],
  ),
  SubCategory(
    main: "Desktops",
    sub: ["Hp", "Dell", "Lenovo", "Apple", "Other"],
  ),
  SubCategory(
    main: "Printers, Scanners & Copiers",
    sub: ["All In One Printers", "Laser Printers", "Inkjet Printers"],
  ),
  SubCategory(
    main: "Cellphone Accessories",
    sub: [
      "Smart Watches",
      "Cases, Covers & Screen Protectors",
      "USB Cables",
      "Phone Batteries & Chargers",
      "Power Banks",
      "SD Cards",
      "Selfie Sticks",
    ],
  ),
  SubCategory(
    main: "Other Electronics",
    sub: ["Other", "Hp"],
  ),
  SubCategory(
    main: "Audio & Video Equipment",
    sub: [
      " Headphones & Earphones",
      "Speakers & Home Stereos",
      "Projectors",
      "DVD & Blu-Ray Players",
      "Compact HiFi Systems",
    ],
  ),
  SubCategory(
    main: "Tablets",
    sub: ["Samsung", "Apple", "Other"],
  ),
  SubCategory(
    main: "Software",
    sub: ["Operating Systems", "Antivirus"],
  ),
  SubCategory(
    main: "Cameras",
    sub: ["Lenses & Camera Accessories", "DSLR Cameras", "Compact Cameras"],
  ),
  SubCategory(
    main: "Video Games & Consoles",
    sub: ["Playstation", "Sony", "Xbox"],
  ),
  SubCategory(
    main: "Building & Trade Services",
    sub: [
      "Builders",
      "Borehole Services",
      "Other Trade Services",
      "Plumbing Services",
      "Electrical Services",
      "Solar Installation Services",
      "Architects & Drawings",
      "Air Conditioning & Refrigeration Services",
      "Water Delivery Services",
      "General Handymen",
    ],
  ),
  SubCategory(
    main: "Security Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Car Rentals & Hire",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Advertising, Marketing & Printing",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Cleaning & Domestic Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Fitness, Beauty & Health Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Business Consultants",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Education, Tuition & Training",
    sub: [
      "Education & Tutors",
      "IT, Technology & Engineering Tuition",
      "Other Training",
      "Business Training",
      "Technicians & Trades Classes",
    ],
  ),
  SubCategory(
    main: "Auto Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Landscaping & Gardening Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Other Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Moving, Transport & Storage",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Computer & IT Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Events, Wedding & Catering",
    sub: [
      "Other Event Services",
      "DJs & Sound Systems For Hire",
      "Baking & Wedding Cakes",
      "Catering",
      "Decor & Flowers For Hire",
      "Venues For Hire",
      "Event Management",
      "Wedding Dress Hire",
      "Kids' Parties",
      "Tents & Marquees For Hire",
    ],
  ),
  SubCategory(
    main: "Funeral Services",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Health, Medical & Beauty",
    sub: [
      "Medical Equipment",
      "Personal Care & Beauty",
      "Medical Supplies",
      "Vitamins & Dietary Supplements",
      "Sexual Wellness",
      "Health & Medical",
    ],
  ),
  SubCategory(
    main: "Home & Kitchen Appliances",
    sub: [
      "Fridges & Freezers",
      "Cookers & Ovens",
      "Kitchen Equipment",
      "Air Conditioners",
      "Washing Machines & Dryers",
      "Microwaves",
      "Heaters",
      "Sewing Machines & Accessories",
      "Vacuum Cleaners",
      "Blenders",
      "Dish Washers",
      "Utensils & Plates",
      "Pots & Pans",
    ],
  ),
  SubCategory(
    main: "Furniture",
    sub: [
      "Chairs & Sofas",
      "Cabinets & Cupboards",
      "Beds & Mattresses",
      "Tables & Desks",
      "Shelving & Storage",
      "Dining Sets",
      "Dressers",
      "Lounge Suites",
      "Other Furniture",
      "TV Stands",
      "Shelving",
    ],
  ),
  SubCategory(
    main: "Baby & Kids Products",
    sub: [
      "Girls Clothing, Fashion",
      "Kids Unisex",
      "Boys Clothing, Fashion",
      "Baby & Kids Furniture",
      "Baby & Kids Accessories",
      "Baby & Kids Shoes",
      "Baby Car Seats & Carriers",
      "Prams & Strollers",
      "Bath Time",
      "Baby & Kids Toys",
    ],
  ),
  SubCategory(
    main: "Home Decor & Bedding",
    sub: [
      "Curtains & Blinds",
      "Duvets, Sheets & Blankets",
      "Paintings & Wall Hangings",
      "Other Home Decor",
      "Carpets & Rugs",
      "Lamps & Lights",
      "Pillows & Cushions",
      "Home Mirrors",
      "Clocks",
    ],
  ),
  SubCategory(
    main: "Pets",
    sub: [
      "Dogs & Puppies",
      "Birds",
      "Pet Accessories",
      "Cats & Kittens",
      "Other Pets",
    ],
  ),
  SubCategory(
    main: "Garden, Patio & Pools",
    sub: [
      "Plants & Pots",
      "Swimming Pools",
      "Outdoor Furniture",
      "Other Garden",
      "Garden Tools",
      "Lawn Mowers",
      "Garden Ornaments",
    ],
  ),
  SubCategory(
    main: "Clothes & Shoes",
    sub: [
      "Women's Clothing",
      "Bags",
      "Wedding Wear",
      "Men's Clothing",
      "Fashion Accessories",
      "Men's Shoes",
      "Women's Shoes",
      "Jewellery",
    ],
  ),
  SubCategory(
    main: "Sports & Fitness Gear",
    sub: [
      "Other Sports & Games",
      "Weights & Gym",
      "Bicycles & Cycling",
      "Leisure",
      "Fitness Products",
      "Soccer",
      "Basketball",
      "Cricket",
      "Fishing",
      "Golf",
      "Racquet Sports",
    ],
  ),
  SubCategory(
    main: "Energy, Batteries, Solar, Gas",
    sub: [
      "Other Energy, Batteries, Solar, Gas",
      "Gas",
      "Batteries",
      "Battery Chargers, Testers",
    ],
  ),
  SubCategory(
    main: "Books",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Cutlery, Crockery & Glassware",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Fixtures, Fittings",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Musical Instruments",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Men",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Women",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Massage",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Friends Only",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Houses for Sale",
    sub: [],
  ),
  SubCategory(
    main: "Land for Sale",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Commercial Property for Sale",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Flats & Apartments for Sale",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Houses to Rent",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Commercial Property to Rent",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Rooms for Rent",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Flats & Apartments for Rent",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
  SubCategory(
    main: "Land to Rent",
    sub: [
      "Manzini",
      "Mbabane",
      "Big Bend",
      "Malkerns",
      "Nhlangano",
      "Mhlume",
      "Hluti",
      "Simunye",
      "Siteki",
      "Piggs Peak",
      "Lobamba",
      "Ngomane",
      "Vuvulane",
      "Mpaka",
      "Kwaluseni",
      "Bhunya",
      "Mhlambanyatsi",
      "Mondi",
      "Tabankulu",
      "Hlatikulu",
      "Bulembu",
      "Kubuta",
      "Tjaneni",
      "Sidvokodvo",
      "Lavumisa",
      "Ngwenya",
      "Nsoko",
      "Mankayane",
    ],
  ),
];
